### PR TITLE
add dbg to silence warning, should eventually be a log message, set m…

### PR DESCRIPTION
**Pull request by zancas**
…ax_width to 80

### CODE REVIEW

**Comment by zancas** [comment]
I'm working on silencing warnings.

**Comment by zancas** [comment]
@AloeareV what do you think of these changes?

**Review by AloeareV — APPROVED** [review]
Looks good! I'm good to merge, but this is still set to draft, so I will await confirmation from you first.

**Comment by zancas** [comment]
OK no longer draft @AloeareV ...

**Comment by AloeareV** [comment]
Meant to get to this earlier, sorry. Merged!

**Pull request merged**
